logging:
  level:
    root: info
    org.hiberante.SQL: debug
    org.hiberante.type: trace
    org.apache.coyote.http11: debug #Http ???? ?? ???

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jpa
    username: sa
    password: 1

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

    hibernate:
      ddl-auto: create

  data:
    web:
      pageable:
        default-page-size: 20

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

server:
  servlet:
    session:
      tracking-modes: cookie